### ISSUE TITLE
Old Android versions does not support modern creating custom events syntax

### ISSUE THREAD

**Issue by renchap** [LouisBrunner/react-dnd-multi-backend#11]
On "old" Android devices (<= 5.0 it seems), https://github.com/LouisBrunner/react-dnd-multi-backend/blob/master/src/lib/MultiBackend.js#L112 fails with a `Type Error (Illegal constructor)` exception.

Old browsers does not accept the modern syntax to create custom events. A workaround is provided on MDN: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way

It would be great to add this alternative syntax in a `try` block, as these versions are quite common for mobile users and this syntax can not be polyfilled. This will also help supporting IE users.

I can provide a PR for this, but I am not sure to understand what `event.constructor(event.type, event)` does here.

**Comment by LouisBrunner** [comment]
Hi @renchap,

Thank you for the report. This problem happen on backend change. When a need to switch is detected, the `MultiBackend` will change the internal backend and redispatch the event that triggered this change to the new backend. However, events can only be dispatched once, so we need to clone it. `event.constructor(event.type, event)` is doing just that, however it's not copying correctly (warning in #10 because `cancelable` is not set to true) and has some issues with older browsers (your issue).

I will look into a way to fix it, but you are welcome to create a PR :)

**Comment by LouisBrunner** [comment]
I fixed it in cd75242bdd48957b0c19a00d6927a9b57def6e80, you can already test it if you want (I will be releasing a patch version soon).

**Comment by renchap** [comment]
Thanks, I will try it. I do not have an old Android device to test it, but I will roll this version in production and see if Sentry reports any new occurrences.

**Comment by LouisBrunner** [comment]
The fix was released in `2.3.8` and `3.0.3`.
Can you confirm it work when you have some time? Thanks!

**Comment by renchap** [comment]
I did not see this error in the wild in the last 2 weeks, so it seems fixed. Thanks!
