### ISSUE TITLE
Compatibility with MouseBackEnd?

### ISSUE THREAD

**Issue by wolfbiter** [LouisBrunner/react-dnd-multi-backend#3]
Hi,

Neither Touch nor HTML5 backends work with svg, but MouseBackEnd does https://github.com/zyzo/react-dnd-mouse-backend.

Do you have any plans to support arbitrary backends with this project? Would love to use this but currently blocked because I need both HTML5 and Mouse backends

**Comment by LouisBrunner** [comment]
Hi!

That's weird because I use TouchBackend with SVG and it works perfectly (I can't use HTML5 anymore). Did you enable the mouse mode of the TouchBackend (`DragDropContext(TouchBackend({ enableMouseEvents: true }));`)?

The point of the MultiBackend is the ability to switch between backends dynamically, so as long as we specify how to transition from one backend to another, we could support arbitrary backends.

Since you posted this issue, I have been thinking about a way to support arbitrary backends, and we could simply specify an object with the backends and the event to switch between them:
```js
DragDropContext(MultiBackend({ backends: [
  {backend: HTML5Backend},
  {backend: TouchBackend, options: {enableMouseEvents: true}, transition: 'touchstart', preview: true},
] }));
```
Which also means I wouldn't have to bundle the HTML5 and Touch backends and the user can choose the ones they want.

The only problem is that I have a lot of backend specific code to make the transition between backends completely smooth. I am not sure this can be done for arbitrary backends.

**Comment by wolfbiter** [comment]
Ah, my bad... `DragDropContext(TouchBackend({ enableMouseEvents: true }));` totally worked. RTFM.

Yeah, realistically your `HTML5Backend` and `TouchBackend` cover my use cases (and probably most) so hard to say how much value is added by arbitrary backend. My issue is solved, feel free to leave this open or close it

**Comment by LouisBrunner** [comment]
No problem. :)

As a matter of fact, I already added the arbitrary backend system. You can get it if you update to `2.4.x`, it works out-of-the-box but you can change the default (HTML5 + Touch) nearly the same way as in my previous comment (see README on the master branch).

I also made a v3 that doesn't include any default so you have to explicitly mention the backends you want (which means Webpack will not include them if you don't use them), it's on npm with the tag `next`.

You probably won't need it, but at least your initial question is finally answered! :D

**Comment by wolfbiter** [comment]
Wow cool! Thanks so much, I'll check it out and give it a whirl

**Comment by LouisBrunner** [comment]
The current version is `2.3.x` tough, my bad.
